name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version --application-name my-app --version-label ${{ github.sha }} --source-bundle S3Bucket="my-bucket",S3Key="my-app/${{ github.sha }}.zip"
        aws elasticbeanstalk update-environment --environment-name my-app-env --version-label ${{ github.sha }}

    - name: Run Health Check
      run: |
        curl -f http://my-app-env-url/health || exit 1

    - name: Rollback if Health Check fails
      if: failure()
      run: |
        aws elasticbeanstalk update-environment --environment-name my-app-env --version-label previous-version
