name: CI/CD for Static HTML/JS/CSS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests (using Node.js)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (for tests)
        run: |
          npm install
          npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cleanup git extraheader
        run: |
          if git config --get-regexp '^http\.https://github\.com/.extraheader$' >/dev/null 2>&1; then
            git config --unset-all http.https://github.com/.extraheader
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_DEPLOY_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "/"

